# Generated by Django 2.2 on 2020-11-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=True, max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=True, max_length=45),
        ),
    ]
